### PR TITLE
Port to webkit2gtk

### LINKED ISSUE #184: Port to webkit2gtk
webkitgtk is deprecated and was replaced by webkit2gtk. It was removed from Arch Linux official repositories and now is only on the AUR.

https://lists.archlinux.org/pipermail/arch-dev-public/2017-June/028900.html

It seems that Remarkable does not work with webkit2gtk. Can you please port it to use webkit2gtk?

### PR DESCRIPTION
**Pull request by timeraider4u**
fixes #184

### CODE REVIEW

**Comment by jayvdb** [comment]
This patch at least gets me started using Remarkable on Fedora Rawhide (27), which appears to also not have 'WebKit' namespace, only having 'WebKit2' (c.f. https://github.com/jamiemcg/Remarkable/issues/183#issuecomment-322354707 )

**Comment by mbloms** [comment]
How do you build this? I can't run it, even though I tried to use the official distribution and patch the files onto it.

**Comment by timeraider4u** [comment]
@mbloms What do you mean with "can't run it"? Can you please clarify what exactly goes wrong?

**Comment by mbloms** [comment]
@timeraider4u I took down the source via AUR, which unpackes the official .deb. I then manually replaced RemarkableWindow.ui and RemarkableWindow.py with your files and tried installing that with pacman. Running it gives me this:
```
(remarkable:8041): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(remarkable:8041): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(remarkable:8041): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/bin/remarkable", line 66, in <module>
    remarkable.main()
  File "/usr/lib/python3.6/site-packages/remarkable/__init__.py", line 52, in main
    window.check_settings() # Load settings after app displayed to fix bugs!
  File "/usr/lib/python3.6/site-packages/remarkable/RemarkableWindow.py", line 219, in check_settings
    self.load_settings()
  File "/usr/lib/python3.6/site-packages/remarkable/RemarkableWindow.py", line 239, in load_settings
    if self.remarkable_settings['js'] == False:
KeyError: 'js'
```

But then again I don't understand why this installation process uses this weird .deb approach. And I don't really understand how to build from source.

**Comment by mbloms** [comment]
I should add that I have no problems with this when I build without patching using webkitgtk.

**Comment by timeraider4u** [comment]
Ah okay, now I see the problem: the "patched" version tries to read a new setting in the configuration file, which cannot be found as it has not been written into this file by previous versions and, therefore, fails. `mv ~/.remarkable/remarkable.settings ~/.remarkable/remarkable.settings.backup` should do the trick.

Seems that my second commit (which enables disabling of java-script execution) might need some re-work.

**Comment by timeraider4u** [comment]
Or you can now re-try with the newest modified version instead of using the `mv`command.

**Comment by mbloms** [comment]
Nice! This seems to work fine. I made a package in the AUR that uses this patch. 📦 
https://aur.archlinux.org/packages/remarkable-webkit2gtk/
#184

**Comment by timeraider4u** [comment]
@mbloms I am not using Arch Linux, but 👍 for your work.

**Comment by mbloms** [comment]
fixes #219, fix #193, fix #183, fix #39.

**Comment by terrafoundry** [comment]
Experiencing this too, is it due to get rolled into a release?

**Comment by mbloms** [comment]
@terrafoundry development on the project is practically on hold indefinitely. If you're on Arch or an Arch-based dist, you can use the mentioned package in the AUR. Otherwise you'll need to install the fork manually.

**Pull request closed without merging**
