### PR TITLE
Upgrading to Webkit2

### PR DESCRIPTION
**Pull request by Deadolus**
On Ubuntu 19.10 Webkit is no longer available.
The package is now gir1.2-webkit2-4.0.
So I upgraded RemarkableWindow to use webkit2.

Note: not sure if there's a equal line to console-message.
I have not seen any distracting messages in the console.
So I removed that line.

### CODE REVIEW

**Comment by Deadolus** [comment]
I just saw that this will/would break the clipboard: 

`AttributeError: 'WebView' object has no attribute 'can_copy_clipboard'
Traceback (most recent call last):
  File "/home/me/workspace/Remarkable/remarkable/RemarkableWindow.py", line 715, in on_menuitem_copy_activate
    def on_menuitem_paste_activate(self, widget):
AttributeError: 'WebView' object has no attribute 'can_copy_clipboard'`

Probably best to avoid merging for now

**Comment by Deadolus** [comment]
I found there's already another port for Webkit2: https://github.com/jamiemcg/Remarkable/pull/185

**Comment by jclaveau** [comment]
> I found there's already another port for Webkit2: #185

It seems to not be up to date and the PR source branch has been deleted

**Comment by Deadolus** [comment]
Added a fix for the clipboard. 
I am not aware of any other issues with migrating to Webkit2.

**Comment by Deadolus** [comment]
I pushed the Webkit2 version to the beta version of https://github.com/jamiemcg/Remarkable/pull/317
Happy for users to try it out, install the Webkit2 version with
`sudo snap install --channel=beta remarkable`

**Comment by jclaveau** [comment]
This one looks like a dup also https://github.com/jamiemcg/Remarkable/issues/193

**Comment by jclaveau** [comment]
Another one https://github.com/jamiemcg/Remarkable/issues/39

**Comment by jclaveau** [comment]
This one also https://github.com/jamiemcg/Remarkable/issues/306

**Pull request merged**
